name: Docker Image CI

on:
  push:
    branches: [ future-perfect ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get version
        run: ./get_version.sh
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        if: env.image_name != 'abort'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: blaseballsibr/prophesizer
          tags: ${{ env.image_name }}
